###############################################################################
##
##  Copyright (C) 2014 Tavendo GmbH
##
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##      http:##www.apache.org#licenses#LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.
##
###############################################################################

Import('env')
#Import('autobahn')

tests = []
if False:
   for i in range(6):
      tests.append(env.Program('test{}.cpp'.format(i + 1), LIBS = [autobahn, 'msgpack']))
else:
   i = 5
   #tests.append(env.Program('test{}.cpp'.format(i + 1), LIBS = [autobahn, 'msgpack']))
   #tests.append(env.Program('test5.cpp', LIBS = ['boost_system', 'boost_thread']))
#   tests.append(env.Program('test5.cpp', LIBS = ['boost_thread', 'boost_system']))
#   tests.append(env.Program('test10.cpp', LIBS = ['boost_thread', 'boost_system']))
#   tests.append(env.Program('test7c.cpp', LIBS = ['boost_thread', 'boost_system', 'msgpack', autobahn]))
#   tests.append(env.Program('test11.cpp', LIBS = ['boost_thread', 'boost_system', 'msgpack', autobahn]))
#   tests.append(env.Program('test_asio.cpp', LIBS = ['boost_thread', 'boost_system', 'msgpack']))
#   tests.append(env.Program('publish.cpp', LIBS = ['boost_thread', 'boost_system', 'msgpack', autobahn]))
   tests.append(env.Program('test13.cpp', LIBS = ['boost_thread', 'boost_system', 'msgpack']))
#   tests.append(env.Program('test15.cpp', LIBS = ['boost_thread', 'boost_system']))
#   tests.append(env.Program('test14.cpp', LIBS = ['boost_thread', 'boost_system']))
#   tests.append(env.Program('test12.cpp', LIBS = ['boost_thread', 'boost_system', 'msgpack']))
#   tests.append(env.Program(['test7.cpp', '#/src/autobahn.cpp'], LIBS = ['boost_thread', 'boost_system', 'msgpack']))
#   tests.append(env.Program(['test7.cpp'], LIBS = ['boost_thread', 'boost_system', 'msgpack']))
#   tests.append(env.Program('test8.cpp', LIBS = ['boost_thread', 'boost_system']))
   #tests.append(env.Program('test6.cpp'))

Return('tests')
