###############################################################################
##
##  Copyright (C) 2014 Tavendo GmbH
##
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.
##
###############################################################################

import os
import json
import pkg_resources

taschenmesser = pkg_resources.resource_filename('taschenmesser', '..')
#taschenmesser = "../../../infrequent/taschenmesser"
env = Environment(tools = ['default', 'taschenmesser'],
                  toolpath = [taschenmesser],
                  ENV = os.environ)


##
## Sphinx Build
##
sphinx_docs = env.Command('_build', [], "sphinx-build -b html . $TARGET")
env.AlwaysBuild(sphinx_docs)
Clean(sphinx_docs, '_build')

uploaded_sphinx = env.s3_dir_uploader('_upload1', '_build', 'autobahn.ws', 'cpp')
Depends(uploaded_sphinx, sphinx_docs)



##
## Doxygen Build
##
doxygen_docs = env.Command('_doxygen', [], "doxygen Doxyfile")
env.AlwaysBuild(doxygen_docs)
Clean(doxygen_docs, '_doxygen')

uploaded_doxygen = env.s3_dir_uploader('_upload2', '_doxygen/html', 'autobahn.ws', 'cpp/reference')
Depends(uploaded_doxygen, doxygen_docs)


##
## Targets
##
Default([sphinx_docs, doxygen_docs])
Alias('upload', [uploaded_sphinx, uploaded_doxygen])
